### PR TITLE
Isobaric cube glass

### PR DESCRIPTION
**Pull request by jaescartin1**

### CODE REVIEW

**Comment by jgphpc** [comment]
cscs-ci run

**Comment by jgphpc** [comment]
cscs-ci run

**Comment by jgphpc** [comment]
cscs-ci run

**Comment by sekelle** [comment]
cscs-ci run

**Comment by sekelle** [comment]
isobaric_ve
isobaric

**Comment by sekelle** [comment]
f4
Test with density ratio of 1:4

**Review by sekelle — APPROVED** [review]

**Review by jaescartin1 — COMMENTED** [review]
Fine with me

**Pull request merged**
