### PR TITLE
Add cmake install target

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
1 need to push 1 more commit

**Comment by jgphpc** [comment]
Check gitlab tests results before merging: [  FAILED  ] Ran 44/46 test case(s) from 46 check(s) (1 failure(s), 2 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13560 github_pr=122
10fc7fe 
```
FAILURE STATISTICS

Total number of test cases: 46
Total number of failures: 1

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
sanity        1     [Run_cascadelake_component_units_cuda, gnu+openmpi, dmi:a100]
------------------------------------------------------------------------------
Run report saved in '/users/staff/dmi-dmi/piccinal/.reframe/reports/run-report.json'
Log file(s) saved in '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13560/reframe/reframe.log', '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13560/reframe/reframe.out'
```

**Comment by jgphpc** [comment]
Check gitlab tests results before merging: [  FAILED  ] Ran 44/46 test case(s) from 46 check(s) (1 failure(s), 2 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13561 github_pr=122
afb3b37 
```
FAILURE STATISTICS

Total number of test cases: 46
Total number of failures: 1

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
sanity        1     [Run_cascadelake_component_units_cuda, gnu+openmpi, dmi:a100]
------------------------------------------------------------------------------
Run report saved in '/users/staff/dmi-dmi/piccinal/.reframe/reports/run-report.json'
Log file(s) saved in '/users/staff/dmi-dmi/piccinal/NATIVE/debug.git/runnerjg/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13561/reframe/reframe.log', '/users/staff/dmi-dmi/piccinal/NATIVE/debug.git/runnerjg/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13561/reframe/reframe.out'
```

**Comment by jgphpc** [comment]
Check gitlab tests results before merging: [  FAILED  ] Ran 44/46 test case(s) from 46 check(s) (1 failure(s), 2 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13562 github_pr=122
b7c8882 
```
FAILURE STATISTICS

Total number of test cases: 46
Total number of failures: 1

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
sanity        1     [Run_cascadelake_component_units_cuda, gnu+openmpi, dmi:a100]
------------------------------------------------------------------------------
Run report saved in '/users/staff/dmi-dmi/piccinal/.reframe/reports/run-report.json'
Log file(s) saved in '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13562/reframe/reframe.log', '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13562/reframe/reframe.out'
```

**Comment by jgphpc** [comment]
Check gitlab tests results before merging: [  FAILED  ] Ran 44/46 test case(s) from 46 check(s) (1 failure(s), 2 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13563 github_pr=122
39f62cd 
```
FAILURE STATISTICS

Total number of test cases: 46
Total number of failures: 1

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
sanity        1     [Run_cascadelake_component_units_cuda, gnu+openmpi, dmi:a100]
------------------------------------------------------------------------------
Run report saved in '/users/staff/dmi-dmi/piccinal/.reframe/reports/run-report.json'
Log file(s) saved in '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13563/reframe/reframe.log', '/users/staff/dmi-dmi/piccinal/SINGULARITY/runner/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13563/reframe/reframe.out'
```

**Review by sekelle — APPROVED** [review]

**Comment by jgphpc** [comment]
Check gitlab tests results before merging: [  FAILED  ] Ran 46/46 test case(s) from 46 check(s) (46 failure(s), 0 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13566 github_pr=122
aa99a5f 
```
FAILURE STATISTICS

Total number of test cases: 46
Total number of failures: 46

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
compile_wait  2     [Build_broadwell, gnu+openmpi, dmi:login]
                    [Build_cascadelake, gnu+openmpi, dmi:login]
startup       44    [Run_broadwell_domain_2ranks, None, None]
                    [Run_broadwell_exchange_focus, None, None]
                    [Run_broadwell_exchange_halos, None, None]
                    [Run_broadwell_globaloctree, None, None]
                    [Run_broadwell_treedomain, None, None]
                    [Run_broadwell_focus_tree, None, None]
                    [Run_broadwell_box_mpi, None, None]
                    [Run_broadwell_exchange_keys, None, None]
                    [Run_broadwell_exchange_domain, None, None]
                    [Run_broadwell_domain_nranks, None, None]
                    [Run_broadwell_hilbert_perf, None, None]
                    [Run_broadwell_peers_perf, None, None]
                    [Run_broadwell_octree_perf, None, None]
                    [Run_broadwell_scan_perf, None, None]
                    [Run_broadwell_sedov, None, None]
                    [Run_broadwell_evrard_new, None, None]
                    [Run_broadwell_component_units, None, None]
                    [Run_broadwell_component_units_omp, None, None]
                    [Run_broadwell_kernel_tests, None, None]
                    [Run_broadwell_coordinate_test, None, None]
                    [Run_broadwell_component_units_cuda, None, None]
                    [Run_broadwell_sedov_cuda, None, None]
                    [Run_cascadelake_domain_2ranks, None, None]
                    [Run_cascadelake_exchange_focus, None, None]
                    [Run_cascadelake_exchange_halos, None, None]
                    [Run_cascadelake_globaloctree, None, None]
                    [Run_cascadelake_treedomain, None, None]
                    [Run_cascadelake_focus_tree, None, None]
                    [Run_cascadelake_box_mpi, None, None]
                    [Run_cascadelake_exchange_keys, None, None]
                    [Run_cascadelake_exchange_domain, None, None]
                    [Run_cascadelake_domain_nranks, None, None]
                    [Run_cascadelake_hilbert_perf, None, None]
                    [Run_cascadelake_peers_perf, None, None]
                    [Run_cascadelake_octree_perf, None, None]
                    [Run_cascadelake_scan_perf, None, None]
                    [Run_cascadelake_sedov, None, None]
                    [Run_cascadelake_evrard_new, None, None]
                    [Run_cascadelake_component_units, None, None]
                    [Run_cascadelake_component_units_omp, None, None]
                    [Run_cascadelake_kernel_tests, None, None]
                    [Run_cascadelake_coordinate_test, None, None]
                    [Run_cascadelake_component_units_cuda, None, None]
                    [Run_cascadelake_sedov_cuda, None, None]
------------------------------------------------------------------------------
Run report saved in '/users/staff/dmi-dmi/piccinal/.reframe/reports/run-report.json'
Log file(s) saved in '/users/staff/dmi-dmi/piccinal/NATIVE/debug.git/runnerjg/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13566/reframe/reframe.log', '/users/staff/dmi-dmi/piccinal/NATIVE/debug.git/runnerjg/builds/AxtzSHcq/0/j.piccinali/mirror_test/tmp.13566/reframe/reframe.out'
```

**Pull request merged**
